on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v3
        with:
          path: |
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev libasound2-dev

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install node modules
        run: yarn install --network-timeout 200000000

      - name: Build app
        run: yarn tauri:bundle

      - name: List files
        if: matrix.platform == 'ubuntu-20.04' || matrix.platform == 'macos-latest'
        run: |
          ls src-tauri/target/release/bundle/*

      - name: List files (windows)
        if: matrix.platform == 'windows-latest'
        run: |
          dir src-tauri\target\release\bundle
          dir src-tauri\target\release\bundle\*
          dir src-tauri\target\release\bundle\msi

      - name: Get version
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Compress (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          cd src-tauri/target/release/bundle
          rm -f ms-beauty${{ env.PACKAGE_VERSION }}.tar.gz
          tar -czvf ms-beauty${{ env.PACKAGE_VERSION }}.tar.gz "macos/Ms Beauty.app"

      - name: Releasing artifacts (macos)
        if: matrix.platform == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/ms-beauty${{ env.PACKAGE_VERSION }}.tar.gz

      - name: Releasing artifacts (ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/appimage/ms-beauty_${{ env.PACKAGE_VERSION }}_amd64.AppImage
            src-tauri/target/release/bundle/deb/ms-beauty_${{ env.PACKAGE_VERSION }}_amd64.deb

      - name: Releasing artifacts (windows)
        if: matrix.platform == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/msi/Ms Beauty_${{ env.PACKAGE_VERSION }}_x64_en-US.msi

      - name: "✏️ Generate release changelog"
        if: matrix.platform == 'ubuntu-20.04'
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}